### ISSUE TITLE
EPIC: prow setup

### ISSUE THREAD

**Issue by raelga** [3scale-ops/test-infra#6]
## Why?

Prow is up and running, but we need some further setup to make it more usefull

## How?

By adding the required Prow functionalities or configurations.

## Requirements

 - [x] Add issue templates for test-infa https://github.com/3scale-ops/test-infra/issues/3
 - [x] Add label management #2
 - [x] Add OWNER and OWNER_ALIASES files to Prow repos #12
 
## Acceptance Criteria

 - [x] https://github.com/3scale-ops/test-infra/issues/3  is closed
 - [x] #2
 - [x] #12 is closed
